#!/usr/bin/env sh

cd $(dirname $0)

build () {
    docker build -t adriensamson/$1 $1
}

if [ -n "$1" ]
then
    build $1
else
    for dir in $(find . -mindepth 1 -maxdepth 1 -type d -name '[^.]*')
    do
        build $(basename $dir)
    done
fi
